version: "3"

networks:
  mynet:
    name: mynet
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
    
services:
  telegram_homepage_db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      mynet:
        ipv4_address: ${WORDPRESS_DB_IP_V4_ADDR}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${WORDPRESS_DB_PORT}:3306
    expose:
      - ${WORDPRESS_DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_MYSQL_DATABASE}
      MYSQL_USER: ${WORDPRESS_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_MYSQL_PASSWORD}
    
  telegram_homepage:
    depends_on:
      - telegram_homepage_db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - ${PORT}:80
    restart: always
    networks: 
      - mynet
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_IP_V4_ADDR}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_MYSQL_DATABASE}